[custom]
;基础配置
enable_rule_generator=true
overwrite_original_rules=true
exclude_remarks=X5|剩余流量|套餐到期|过滤掉|专线去油管广告|请每月更|白嫖机场.com-官网|Youtube破解广告|ipv6免流

;规则
ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PrivateTracker.list
ruleset=国内直连,https://raw.githubusercontent.com/zhaoxp520/rules/Clash/ruleset/NET.list
ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
ruleset=国外网盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=国外网盘,https://raw.githubusercontent.com/ColinLeeeee/ColinRule/master/GoogleDrive.list
ruleset=微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
ruleset=PayPal,https://raw.githubusercontent.com/zhaoxp520/rules/Clash/ruleset/PayPal.list
ruleset=ChatGPT,https://raw.githubusercontent.com/zhaoxp520/rules/Clash/ruleset/ChatGPT.list
ruleset=社交平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Facebook.list
ruleset=社交平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list
ruleset=社交平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
ruleset=社交平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Line.list
ruleset=社交平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Whatsapp.list
ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=NETFLIX,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=NETFLIX,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list
ruleset=MyTVSuper,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/MyTVSuper.list
ruleset=巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=不可描述,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Download.list
ruleset=国内直连,[]GEOIP,CN
ruleset=其他流量,[]FINAL

;分组
custom_proxy_group=节点选择`select`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=YouTube`select`[]香港节点`[]节点选择`[]自动选择`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=NETFLIX`select`[]新加坡节点`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]国内直连`.*
custom_proxy_group=MyTVSuper`select`[]香港节点`.(香港)
custom_proxy_group=巴哈姆特`select`[]台湾节点`.(台湾)`
custom_proxy_group=国外媒体`select`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=国内媒体`select`[]国内直连`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`.*
custom_proxy_group=谷歌FCM`select`[]香港节点`[]节点选择`[]自动选择`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=社交平台`select`[]香港节点`[]节点选择`[]自动选择`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=Telegram`select`[]新加坡节点`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]国内直连`.*
custom_proxy_group=PayPal`url-test`(美国)`http://www.gstatic.com/generate_204`900
custom_proxy_group=ChatGPT`url-test`(美国)`http://www.gstatic.com/generate_204`900
custom_proxy_group=国外网盘`select`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=游戏平台`select`[]国内直连`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`.*
custom_proxy_group=不可描述`select`[]香港节点`[]节点选择`[]自动选择`[]台湾节点`[]日本节点`[]新加坡节点`[]国内直连`.*
custom_proxy_group=苹果服务`select`[]国内直连`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`.*
custom_proxy_group=微软服务`select`[]国内直连`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`.*
custom_proxy_group=国内直连`select`[]DIRECT`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`.*
custom_proxy_group=其他流量`select`[]国内直连`[]节点选择`[]自动选择`[]香港节点`[]台湾节点`[]日本节点`[]新加坡节点`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`900
custom_proxy_group=香港节点`url-test`(香港)`http://www.gstatic.com/generate_204`900
custom_proxy_group=台湾节点`url-test`(台湾)`http://www.gstatic.com/generate_204`900
custom_proxy_group=日本节点`url-test`(日本)`http://www.gstatic.com/generate_204`900
custom_proxy_group=新加坡节点`url-test`(新加坡)`http://www.gstatic.com/generate_204`900
